-- Run this script in Supabase SQL editor.
-- It creates a full chat schema compatible with the app.

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_email text not null,
  message text not null,
  room text not null default 'global' check (room in ('global', 'dev', 'random')),
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

alter table public.messages enable row level security;

-- Anyone signed in can read messages.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'messages' and policyname = 'messages_select_authenticated'
  ) then
    create policy messages_select_authenticated
      on public.messages
      for select
      to authenticated
      using (true);
  end if;
end
$$;

-- Signed-in users can insert only with their own auth email.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'messages' and policyname = 'messages_insert_own_email'
  ) then
    create policy messages_insert_own_email
      on public.messages
      for insert
      to authenticated
      with check (auth.email() = user_email);
  end if;
end
$$;

-- Signed-in users can update only their own messages.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'messages' and policyname = 'messages_update_own_email'
  ) then
    create policy messages_update_own_email
      on public.messages
      for update
      to authenticated
      using (auth.email() = user_email)
      with check (auth.email() = user_email);
  end if;
end
$$;

-- Signed-in users can delete only their own messages.
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'messages' and policyname = 'messages_delete_own_email'
  ) then
    create policy messages_delete_own_email
      on public.messages
      for delete
      to authenticated
      using (auth.email() = user_email);
  end if;
end
$$;

create index if not exists messages_room_created_idx on public.messages (room, created_at);
create index if not exists messages_user_idx on public.messages (user_email);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'messages'
  ) then
    alter publication supabase_realtime add table public.messages;
  end if;
end
$$;
